### PR TITLE
Remove prop-types

### PR DESCRIPTION
**Pull request by dsgkirkby**
These are slow to compute in dev, particularly on the planning
page, and are unnecessary as we have typescript to statically
check things for us.

I tried this locally and navigating the planning tree in dev is
dramatically faster.

### CODE REVIEW

**Review by JustinZhengBC — APPROVED** [review]
Looks reasonable, should we get rid of all the proptypes? There's still some left

**Comment by dsgkirkby** [comment]
The only other ones are in a test component I think?

**Comment by JustinZhengBC** [comment]
They seem to be from smaller type definitions within the files as opposed to the main component

```
grep propTypes -i -r src/**/*.js
src/FilteringContainer.js:import PropTypes from 'prop-types';
src/FilteringContainer.js:    unfilteredNodes: PropTypes.arrayOf(PropTypes.shape(Node)).isRequired,
src/TreeContainer.js:import PropTypes from 'prop-types';
src/TreeContainer.js:    unfilteredNodes: PropTypes.arrayOf(PropTypes.shape(Node)),
src/UnstableFastTree.js:import PropTypes from 'prop-types';
src/UnstableFastTree.js:    unfilteredNodes: PropTypes.arrayOf(PropTypes.shape(Node)),
src/shapes/nodeShapes.js:import PropTypes from 'prop-types';
src/shapes/nodeShapes.js:  expanded: PropTypes.bool,
src/shapes/nodeShapes.js:  deletable: PropTypes.bool,
src/shapes/nodeShapes.js:  favorite: PropTypes.bool,
src/shapes/nodeShapes.js:  id: PropTypes.oneOfType([PropTypes.number, PropTypes.string]).isRequired,
src/shapes/nodeShapes.js:  name: PropTypes.string,
src/shapes/nodeShapes.js:  state: PropTypes.shape(NodeState),
src/shapes/nodeShapes.js:Node.children = PropTypes.arrayOf(PropTypes.shape(Node));
src/shapes/nodeShapes.js:  deepness: PropTypes.number.isRequired,
src/shapes/nodeShapes.js:  parents: PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.number, PropTypes.string])),
src/shapes/rendererShapes.js:import PropTypes from 'prop-types';
src/shapes/rendererShapes.js:  measure: PropTypes.func,
src/shapes/rendererShapes.js:  onChange: PropTypes.func.isRequired,
src/shapes/rendererShapes.js:  node: PropTypes.shape(FlattenedNode),
src/shapes/rendererShapes.js:  index: PropTypes.number.isRequired,
```

**Comment by dsgkirkby** [comment]
I think some of these are used for `contextTypes`, which isn't covered by typescript and isn't what's slow, so didn't seem worth to remove, and the others aren't actually components but rather standard 'types' for this library's prop-types

**Pull request merged**
